# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
resources:
  repositories:
  - repository: githubrepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: lmartinezs
    name: lmartinezs/nousfdemo
variables:
  GIT_COMMIT: $(Build.SourceVersion)
  GIT_BRANCH: $(Build.SourceBranchName)
  CURRENT_PRERELEASE: 12
  PRE_RELEASE_BRANCH: none
  PRE_RELEASE: PRE_RELEASE

jobs:
  - job: check_prerelease
    steps:
    - checkout: githubrepo
    - script: | 
            if [[ $(gh release list | grep -E 'Draft|Pre-release' | wc -l) -ne 0 ]]; then
              echo "There is an open Pre-release"
              PRE_RELEASE=current_one
              PRE_RELEASE_BRANCH=rc/$(gh release list | grep -E 'Pre-release' | awk -F' ' '{print $1}')
              #echo "PRE_RELEASE_BRANCH=$(PRE_RELEASE_BRANCH)" >> $GITHUB_ENV
              echo "##vso[task.setvariable variable=PRE_RELEASE_BRANCH]$PRE_RELEASE_BRANCH"
              LATEST_PRERELEASE_TAG=$(gh release list | grep -E 'Pre-release' | awk -F' ' '{print $3}')
              echo "##vso[task.setvariable variable=CURRENT_PRERELEASE]$LATEST_PRERELEASE_TAG"
              echo "Current Pre-release: $LATEST_PRERELEASE_TAG in branch $PRE_RELEASE_BRANCH"
            else
              PRE_RELEASE=new_one
            fi
            #echo "PRE_RELEASE=$PRE_RELEASE"  >> $GITHUB_ENV
            echo "##vso[task.setvariable variable=PRE_RELEASE]$PRE_RELEASE"
            echo $PRE_RELEASE
            echo "##vso[task.setvariable variable=open_pr;isOutput=true]current_one" #set variable doThing to Yes

      displayName: 'check_open_prerelease'
      name: check_open_prerelease
      env:
        GH_TOKEN: $(gh_token)
    - script: | 
        echo $(GIT_COMMIT)
        echo $(GIT_BRANCH)
        echo $(CURRENT_PRERELEASE)
        echo $(PRE_RELEASE)
      displayName: 'Run a multi-line script'
  - job: create_new_pre_prelease
    dependsOn: check_prerelease
    condition: eq(dependencies.check_prerelease.outputs['check_open_prerelease.open_pr'], 'new_one') #map doThing and check the value
    steps: 
    - script: 'echo new one hello world'
  - job: push_to_current_prerelease
    dependsOn: check_prerelease
    condition: eq(variables.PRE_RELEASE, 'current_one')
    steps: 
    - script: 'echo current hello world'